context:
  version: 2.4.1

package:
  name: copyfiles
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/copyfiles/-/copyfiles-${{ version }}.tgz
  sha256: a2bb739817cbb95f737edb9acaacc4f9f587debbf5acfc6f5cdac4c641dedbd7

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - copyfiles --help

about:
  license: MIT
  license_file:
    - license.md
    - third-party-licenses.txt
  summary: copy files on the command line
  homepage: https://github.com/calvinmetcalf/copyfiles
  repository: https://github.com/calvinmetcalf/copyfiles

extra:
  recipe-maintainers:
    - danielnachun
